height: 476
width: 630

encoder_path: "models/DINOv2/dinov2_vits14_reg4_pretrain.pth"
patch: 14

train:
  dataset_path: "data/train/DJIAction4/"
  result_path: "result/train/"
  batch_size: 16
  gpu_id: 0
  epoch: 1
  loss_lambda: 1.0

eval:
  model_path: "models/IOPEN/latest.pth"
  # original_img_dir: "data/eval/frame/"
  # masked_img_dirs: ["data/eval/masked_l/", "data/eval/masked_r/"]
  # output_dir: "data/eval/result/"
  frame_cnt: 10
  original_img_dir: "data/validate/rgb/"
  masked_img_dirs: ["data/validate/masked/"]
  output_dir: "data/validate/result/"